// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQblAO8t-KGFUFrqmJDWQLczFPO8RZAqQ',
    appId: '1:335780341856:web:99d1dbb7340fa0c60ffb05',
    messagingSenderId: '335780341856',
    projectId: 'to-do-3ca98',
    authDomain: 'to-do-3ca98.firebaseapp.com',
    storageBucket: 'to-do-3ca98.firebasestorage.app',
    measurementId: 'G-RVS1HTTEVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXJ1HjJZMH304dvaYnKZdmIZ-balG9G2g',
    appId: '1:335780341856:android:f632b113807b79d30ffb05',
    messagingSenderId: '335780341856',
    projectId: 'to-do-3ca98',
    storageBucket: 'to-do-3ca98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW2pAzZlMdUyxQSRogBn38SPqRkRMCTyQ',
    appId: '1:335780341856:ios:905467b23b6655f90ffb05',
    messagingSenderId: '335780341856',
    projectId: 'to-do-3ca98',
    storageBucket: 'to-do-3ca98.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW2pAzZlMdUyxQSRogBn38SPqRkRMCTyQ',
    appId: '1:335780341856:ios:905467b23b6655f90ffb05',
    messagingSenderId: '335780341856',
    projectId: 'to-do-3ca98',
    storageBucket: 'to-do-3ca98.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQblAO8t-KGFUFrqmJDWQLczFPO8RZAqQ',
    appId: '1:335780341856:web:33d44ff4f13a94db0ffb05',
    messagingSenderId: '335780341856',
    projectId: 'to-do-3ca98',
    authDomain: 'to-do-3ca98.firebaseapp.com',
    storageBucket: 'to-do-3ca98.firebasestorage.app',
    measurementId: 'G-EJFC4PV6XB',
  );
}
